steps:
  # - name: 'gcr.io/cloud-builders/docker'
  #   entrypoint: 'bash'
  #   args: [
  #     '-c',
  #     'docker pull europe-docker.pkg.dev/${PROJECT_ID}/docker-repo/hello:latest || exit 0'
  #   ]

  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build",
      "--file", "ops/docker_files/deploy.dockerfile",
      "-t", "europe-docker.pkg.dev/${PROJECT_ID}/docker-repo/hello:$SHORT_SHA",
      "-t", "europe-docker.pkg.dev/${PROJECT_ID}/docker-repo/hello:latest",
      "--build-arg", "github_sha=$COMMIT_SHA",
      "."
    ]

images: [
  "europe-docker.pkg.dev/${PROJECT_ID}/docker-repo/hello:$SHORT_SHA",
  "europe-docker.pkg.dev/${PROJECT_ID}/docker-repo/hello:latest"
]

  # # deploy container image to GKE
  # - name: "gcr.io/cloud-builders/gke-deploy"
  #   args:
  #   - run
  #   - --filename=kubernetes-resource-file
  #   - --image=europe-docker.pkg.dev/${PROJECT_ID}/docker-repo/hello:$SHORT_SHA
  #   - --location=europe-b
  #   - --cluster=jafolders-cluster-3

# options:
#   machineType: 'E2_HIGHCPU_8'
